[env]
WINIT_X11_SCALE_FACTOR = "1"

[font.bold]
family = "HackNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "HackNerdFontMono"
style = "BoldItalic"

[font.italic]
family = "HackNerdFontMono"
style = "Italic"

[font.normal]
family = "HackNerdFontMono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control"

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Fullscreen"
